# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cityeye_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: postgres:16
    container_name: cityeye_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cityeye_db
      POSTGRES_USER: cityeye
      POSTGRES_PASSWORD: 1958?aA
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  pgdata:
