version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cityeye_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: cityeye_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cityeye_db
      POSTGRES_USER: cityeye
      POSTGRES_PASSWORD: 19581123?aA
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
